### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by EmmanuelMess** [EmmanuelMess/Simple-Accounting#42]
```
12-24 20:54:05.631 18192-18192/com.emmanuelmess.simpleaccounting E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: com.emmanuelmess.simpleaccounting, PID: 18192
                                                                                   java.lang.IndexOutOfBoundsException
                                                                                       at java.util.Collections.swap(Collections.java:1937)
                                                                                       at com.emmanuelmess.simpleaccounting.activities.dialogs.CurrencyPicker.swap(CurrencyPicker.java:431)
                                                                                       at com.emmanuelmess.simpleaccounting.activities.dialogs.CurrencyPicker.access$1000(CurrencyPicker.java:42)
                                                                                       at com.emmanuelmess.simpleaccounting.activities.dialogs.CurrencyPicker$4.move(CurrencyPicker.java:354)
                                                                                       at com.emmanuelmess.simpleaccounting.activities.dialogs.CurrencyPicker$4.onTouch(CurrencyPicker.java:326)
                                                                                       at android.view.View.dispatchTouchEvent(View.java:9293)
```

**Comment by natrius** [comment]
The app crashed here too, Version 1.5.2, Android 8.1, OnePlus 3, LineageOS 15.1, when adding a new credit or a debit the app jus crashes. When opening again, there is a second entry without any data in there. 
I could maybe provide a logcat, if you need.

**Comment by EmmanuelMess** [comment]
@natrius you should probably open another issue with the logcat
